"""
Django settings for athena project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import configparser

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "sv@ah$i@6-8i=e^wt8h+n0hwb-)h^_#f^%lpkur&0p1ew&^f)0"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "djangobower",  # for front_end dependencies
    "schemas",  # first_app
    "profil",  # user management
    "wizard",  # privileged athena console management
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "athena.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "athena.wsgi.application"

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# Get database configuration from local.ini
conf_DB = BASE_DIR + "/lib/static/local.ini"
Config = configparser.ConfigParser()
Config.read(os.path.expanduser(conf_DB))

NAME = Config["postgres"]["NAME"]
USER = Config["postgres"]["USER"]
PASSWORD = Config["postgres"]["PASSWORD"]
HOST = Config["postgres"]["HOST"]
PORT = Config["postgres"]["PORT"]

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",  # 'django.db.backends.postgresql',
        "NAME": NAME,
        "USER": USER,
        "PASSWORD": PASSWORD,
        "HOST": HOST,
        "PORT": PORT,
    },
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "djangobower.finders.BowerFinder",
)

BOWER_COMPONENTS_ROOT = os.path.join(BASE_DIR, "components")

BOWER_PATH = "/usr/local/bin/bower"

STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

LOGIN_URL = "/user/login"
LOGIN_REDIRECT_URL = "/"

# Get mail configuration from mail.ini
conf_mail = BASE_DIR + "/lib/static/mail.ini"
Config = configparser.ConfigParser()
Config.read(os.path.expanduser(conf_mail))

EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = Config["mail"]["DEFAULT_FROM_EMAIL"]
SERVER_EMAIL = Config["mail"]["SERVER_EMAIL"]
EMAIL_HOST = Config["mail"]["EMAIL_HOST"]
EMAIL_PORT = Config["mail"]["EMAIL_PORT"]
EMAIL_HOST_USER = Config["mail"]["EMAIL_HOST_USER"]
EMAIL_HOST_PASSWORD = Config["mail"]["EMAIL_HOST_PASSWORD"]
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
