# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_id', models.CharField(max_length=20)),
                ('product_id', models.CharField(max_length=20)),
                ('store_id', models.CharField(max_length=100)),
                ('sales_unit', models.IntegerField()),
                ('sales_cost', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
    ]
