# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemas', '0002_delete_salesschema'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
