# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_salesschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesschema',
            name='name',
            field=models.CharField(default='d', max_length=50),
            preserve_default=False,
        ),
    ]
