# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_auto_20170323_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='thdApsw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('html_type', models.CharField(max_length=20)),
                ('attribute', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thdInv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('html_type', models.CharField(max_length=20)),
                ('attribute', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thdMargin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('html_type', models.CharField(max_length=20)),
                ('attribute', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thdReceipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('html_type', models.CharField(max_length=20)),
                ('attribute', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
