# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0006_thdapsw_thdinv_thdmargin_thdreceipts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thdapsw',
            name='html_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20),
        ),
        migrations.AlterField(
            model_name='thdinv',
            name='html_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20),
        ),
        migrations.AlterField(
            model_name='thdmargin',
            name='html_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20),
        ),
        migrations.AlterField(
            model_name='thdreceipts',
            name='html_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20),
        ),
        migrations.AlterField(
            model_name='thdsales',
            name='html_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20),
        ),
    ]
