# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0007_auto_20170323_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testschema',
            old_name='name',
            new_name='label',
        ),
        migrations.AddField(
            model_name='testschema',
            name='html_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], default='text', max_length=20),
            preserve_default=False,
        ),
    ]
