# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0008_auto_20170323_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testschema',
            name='label',
        ),
        migrations.RemoveField(
            model_name='thdapsw',
            name='label',
        ),
        migrations.RemoveField(
            model_name='thdinv',
            name='label',
        ),
        migrations.RemoveField(
            model_name='thdmargin',
            name='label',
        ),
        migrations.RemoveField(
            model_name='thdreceipts',
            name='label',
        ),
        migrations.RemoveField(
            model_name='thdsales',
            name='label',
        ),
    ]
