# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0009_auto_20170324_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='thdAUTH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('html_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
