# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0010_thdauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testschema',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50),
        ),
        migrations.AlterField(
            model_name='thdapsw',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50),
        ),
        migrations.AlterField(
            model_name='thdauth',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50),
        ),
        migrations.AlterField(
            model_name='thdinv',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50),
        ),
        migrations.AlterField(
            model_name='thdmargin',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50),
        ),
        migrations.AlterField(
            model_name='thdreceipts',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50),
        ),
        migrations.AlterField(
            model_name='thdsales',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50),
        ),
    ]
