# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0012_thdudsv'),
    ]

    operations = [
        migrations.CreateModel(
            name='thdCATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50)),
                ('html_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thdCATR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50)),
                ('html_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thdCLST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50)),
                ('html_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thdLOCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50)),
                ('html_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thdPGAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50)),
                ('html_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thdPGHD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50)),
                ('html_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thdPGSR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50)),
                ('html_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thdPRDH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50)),
                ('html_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thdPSPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50)),
                ('html_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thdPSSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50)),
                ('html_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thdSKUA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50)),
                ('html_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thdSKUM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50)),
                ('html_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thdSTRM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50)),
                ('html_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thdSTRT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50)),
                ('html_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thdUDSG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50)),
                ('html_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
