# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0013_thdcatm_thdcatr_thdclst_thdloch_thdpgad_thdpghd_thdpgsr_thdprdh_thdpspc_thdpssd_thdskua_thdskum_thds'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('string', 'string'), ('tinyint', 'tinyint'), ('smallint', 'smallint'), ('int', 'int'), ('bigint', 'bigint'), ('boolean', 'boolean'), ('float', 'float'), ('double', 'double'), ('array', 'array'), ('map', 'map'), ('timestamp', 'timestamp')], max_length=50)),
                ('html_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
