# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0016_delete_s3info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testSchema',
        ),
        migrations.DeleteModel(
            name='thdApsw',
        ),
        migrations.DeleteModel(
            name='thdAUTH',
        ),
        migrations.DeleteModel(
            name='thdCATM',
        ),
        migrations.DeleteModel(
            name='thdCATR',
        ),
        migrations.DeleteModel(
            name='thdCLST',
        ),
        migrations.DeleteModel(
            name='thdInv',
        ),
        migrations.DeleteModel(
            name='thdLOCH',
        ),
        migrations.DeleteModel(
            name='thdMargin',
        ),
        migrations.DeleteModel(
            name='thdPGAD',
        ),
        migrations.DeleteModel(
            name='thdPGHD',
        ),
        migrations.DeleteModel(
            name='thdPGSR',
        ),
        migrations.DeleteModel(
            name='thdPRDH',
        ),
        migrations.DeleteModel(
            name='thdPSPC',
        ),
        migrations.DeleteModel(
            name='thdPSSD',
        ),
        migrations.DeleteModel(
            name='thdReceipts',
        ),
        migrations.DeleteModel(
            name='thdSales',
        ),
        migrations.DeleteModel(
            name='thdSKUA',
        ),
        migrations.DeleteModel(
            name='thdSKUM',
        ),
        migrations.DeleteModel(
            name='thdSTRM',
        ),
        migrations.DeleteModel(
            name='thdSTRT',
        ),
        migrations.DeleteModel(
            name='thdUDSG',
        ),
        migrations.DeleteModel(
            name='thdUDSV',
        ),
    ]
