# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 09:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='configObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('headers', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='s3Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('shortcut', models.CharField(max_length=20)),
                ('bucket_name', models.CharField(max_length=50, unique=True)),
                ('bucket_region', models.CharField(choices=[('us-east-1', 'us-east-1'), ('us-east-2', 'us-east-2'), ('us-west-1', 'us-west-1'), ('us-west-2', 'us-west-2'), ('ap-south-1', 'ap-south-1'), ('ap-northeast-1', 'ap-northeast-1'), ('ap-northeast-2', 'ap-northeast-2'), ('ap-southeast-1', 'ap-southeast-1'), ('ap-southeast-2', 'ap-southeast-2'), ('eu-central-1', 'eu-central-1'), ('eu-west-1', 'eu-west-1'), ('eu-west-2', 'eu-west-2')], max_length=20)),
                ('type', models.CharField(choices=[('private', 'private'), ('public', 'public')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='configobject',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.s3Info'),
        ),
    ]
