# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 11:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0004_auto_20170427_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configobject',
            name='headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
