# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 10:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0005_auto_20170428_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='fieldsFDV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.configObject')),
            ],
        ),
    ]
