# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0007_auto_20170504_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configobject',
            old_name='fields',
            new_name='fieldsFDV',
        ),
    ]
