# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 17:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0008_auto_20170504_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configobject',
            name='fieldsFDV',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
